    package br.com.gaiatosfc.model;
// Generated 22/04/2016 14:13:13 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Jogadores generated by hbm2java
 */
@Entity
@Table(name="jogadores"
    ,catalog="gaiatosfc"
)
public class Jogadores  implements java.io.Serializable {


     private int codJd;
     private String nomeJd;
     private String foto;
     private String posicao;
     private String jogosDisputados;
     private String gols;
     private String numeroCamisa;
     private String dataNasc;
     private Set golses = new HashSet(0);

    public Jogadores() {
    }

	
    public Jogadores(int codJd, String nomeJd) {
        this.codJd = codJd;
        this.nomeJd = nomeJd;
    }
    public Jogadores(int codJd, String nomeJd, String foto, String posicao, String jogosDisputados, String gols, String numeroCamisa, String dataNasc, Set golses) {
       this.codJd = codJd;
       this.nomeJd = nomeJd;
       this.foto = foto;
       this.posicao = posicao;
       this.jogosDisputados = jogosDisputados;
       this.gols = gols;
       this.dataNasc = dataNasc;
       this.numeroCamisa = numeroCamisa;
       this.golses = golses;
    }
   
    @Id
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="cod_jd", unique=true, nullable=false)
    public int getCodJd() {
        return this.codJd;
    }
    
    public void setCodJd(int codJd) {
        this.codJd = codJd;
    }

    
    @Column(name="nome_jd", nullable=false, length=40)
    public String getNomeJd() {
        return this.nomeJd;
    }
    
    public void setNomeJd(String nomeJd) {
        this.nomeJd = nomeJd;
    }

    
    @Column(name="foto")
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }

    
    @Column(name="posicao", length=30)
    public String getPosicao() {
        return this.posicao;
    }
    
    public void setPosicao(String posicao) {
        this.posicao = posicao;
    }

    
    @Column(name="jogos_disputados")
    public String getJogosDisputados() {
        return this.jogosDisputados;
    }
    
    public void setJogosDisputados(String jogosDisputados) {
        this.jogosDisputados = jogosDisputados;
    }
    
     @Column(name="numero_camisa")
    public String getNumeroCamisa(){
        return numeroCamisa;
    }
    
    public void setNumeroCamisa(String numeroCamisa){
        this.numeroCamisa = numeroCamisa;
    }

    
    @Column(name="gols")
    public String getGols() {
        return this.gols;
    }
    
    public void setGols(String gols) {
        this.gols = gols;
    }

    
    @Column(name="data_nasc", length=13)
    public String getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(String dataNasc) {
        this.dataNasc = dataNasc;
    }
    
    
    @OneToMany(fetch=FetchType.LAZY, mappedBy="jogadores")
    public Set<Gols> getGolses() {
        return this.golses;
    }
    
    public void setGolses(Set golses) {
        this.golses = golses;
    }
}


